version: 0.2

phases:

  install:
    commands:
      - "apt install unzip -y"
      - "wget https://releases.hashicorp.com/terraform/1.2.8/terraform_1.2.8_linux_amd64.zip"
      - "unzip terraform_1.2.8_linux_amd64.zip"
      - "mv terraform /usr/local/bin/"
  pre_build:
    commands:
      - terraform init
      - pwd
      - ls -la
      - cat ./dev/terraform.tfvars
      - cat dev/terraform.tfvars

  build:
    commands:
      - terraform apply -var-file="dev/terraform.tfvars"  -auto-approve

  post_build:
    commands:
      - echo terraform apply -var-file="dev/terraform.tfvars"  completed on `date`