version: 0.2

phases:

  install:
    commands:
      - "apt install unzip -y"
      - "wget https://releases.hashicorp.com/terraform/0.11.14/terraform_0.11.14_linux_amd64.zip"
      - "unzip terraform_0.11.14_linux_amd64.zip"
      - "mv terraform /usr/local/bin/"
  pre_build:
    commands:
      - terraform init

  build:
    commands:
      - terraform apply -var-file=\"dev/terraform.tfvars\" -auto-approve

  post_build:
    commands:
      - echo terraform apply -var-file=\"dev/terraform.tfvars\" completed on `date`