env_prefix = "dev"
region ="eu-central-1"
codestar_connection_arn = "*"
github_organization = "anubhav1"
github_repository = "ghost-project"
github_branch ="master"
codepipeline_artifacts_bucket = "codepipeline-artifacts-bucket78277"
tf_command = "apply -var-file=\"dev/terraform.tfvars\""
